name: Github python package release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-on-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PyInstaller Windows
        uses: gcandau/pyinstaller-action-windows@python3-12-pyinstaller-6-6
        with:
          path: src
      - uses: actions/upload-artifact@v2
        with:
          name: CellaDispatcher
          path: src/dist/windows
      - name: Zip artifact for deployment
        run: zip -j src/dist/windows/CellaDispatcher.zip src/dist/windows/*.exe
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            src/dist/windows/*.zip
            src/CellaDispatcher.ini
            LICENSE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GPAT_PACKAGE_TOKEN }}
